// generated by the following code:
//
// JSON.stringify(require('gradient-string')([
// { color: '#1a72d1', pos: 0 },
// { color: '#c43af2', pos: 0.9 },
// { color: '#c43af2', pos: 1 },
// ])('Loi-快速搭建自己的Vue项目'))
//
// Use the output directly here to keep the bundle small.

const banner =
  '\x1B[38;2;26;114;209mL\x1B[39m\x1B[38;2;38;110;211mo\x1B[39m\x1B[38;2;50;106;214mi\x1B[39m\x1B[38;2;62;102;216m-\x1B[39m\x1B[38;2;75;98;218m\u5FEB\x1B[39m\x1B[38;2;87;94;221m\u901F\x1B[39m\x1B[38;2;99;90;223m\u642D\x1B[39m\x1B[38;2;111;86;226m\u5EFA\x1B[39m\x1B[38;2;123;82;228m\u81EA\x1B[39m\x1B[38;2;135;78;230m\u5DF1\x1B[39m\x1B[38;2;147;74;233m\u7684\x1B[39m\x1B[38;2;160;70;235mV\x1B[39m\x1B[38;2;172;66;237mu\x1B[39m\x1B[38;2;184;62;240me\x1B[39m\x1B[38;2;196;58;242m\u9879\x1B[39m\x1B[38;2;196;58;242m\u76EE\x1B[39m'

export default banner
